### ISSUE TITLE
Invalid HGT size

### ISSUE THREAD

**Issue by sikmir** [wladich/elevation_server#2]
```sh
$ wget http://viewfinderpanoramas.org/dem1/O35.zip
$ unzip O35.zip
$ make_data -hgt O35 -out dem_tiles
0 / 24 [_________________________________________________________________] 0.00% Elapsed       0s 0s
panic: invalid HGT size

goroutine 1 [running]:
main.makeTiles(0x7fff7d46168e, 0x4, 0x7fff7d461698, 0x9, 0x5)
	github.com/wladich/elevation_server/cmd/make_data/main.go:161 +0x389
main.main()
	github.com/wladich/elevation_server/cmd/make_data/main.go:181 +0x17c
$ ls -lh O35
total 594M
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N56E024.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N56E025.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N56E026.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N56E027.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N56E028.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N56E029.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N57E024.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N57E025.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N57E026.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N57E027.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N57E028.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N57E029.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N58E024.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N58E025.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N58E026.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N58E027.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N58E028.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N58E029.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N59E024.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N59E025.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N59E026.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N59E027.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N59E028.hgt
-rw-r--r-- 1 sikmir users 25M 26. 5.  2014 N59E029.hgt
```

**Comment by wladich** [comment]
1 arc-second hgt files are not supported. Please see [readme file](https://github.com/wladich/elevation_server#prepare-data)
